### ISSUE TITLE
sessions + interaction with secure session

### ISSUE THREAD

**Issue by Danack** [bryanjhv/slim-session#21]
Hi,

I've been using this library with https://github.com/ezimuel/PHP-Secure-Session to have the session data be encrypted.

The two libraries don't actually play that nicely with each other currently, in particular in the behaviour about the refreshing of sessions.

In theory, would you be interested in pull request that make the two libraries work together better or possibly just add the encryption stuff to this library? 

Or would you consider that out of scope for this library, in which case I'd be better off making my own version* ?

*with blackjack! And cake!

**Comment by bryanjhv** [comment]
Sorry for the late reply.

Can you provide a sample of how are you integrating this module with the one you mentioned?
That module looks promising, but integration should be optional, like `autorefresh` and others. If that's fine, you're welcome to do a PR. :smile:

**Comment by Danack** [comment]
> Sorry for the late reply.

Ha - I normally only say that for my repos if more than 2 months have passed since someone opened a ticket.

> Can you provide a sample of how are you integrating this module with the one you mentioned?

It's currently a mess. The ezimuel/PHP-Secure-Session module loads itself automatically by having a 'files' entry in the composer.json of that library.

That sets up a custom SessionHandlerInterface, which makes all the internal PHP function that writes the session data go through [this code](https://github.com/ezimuel/PHP-Secure-Session/blob/6ddb28c175a4747fcf9a68a439ce6aad5b1d0b95/src/SecureHandler.php#L72-L103) to encrypt the data.

Additionally because your library does automatic renewing of sessions, and the PHP-Secure-Session handler isn't aware of that, I need to do a hack to renew the session encryption data, see below. 

I'll see how possible it is to integrate the two but only as an option...


```
<?php

namespace MyProject\Middleware;

class Session extends SlimSession
{
    public function __invoke(Request $request, Response $response, callable $next)
    {
        try {
            $this->startSession();

            return $next($request, $response);
        }
        catch (\RuntimeException $re) {
            // TODO - persuade the library maintainer to use a specific extension
            // https://github.com/ezimuel/PHP-Secure-Session/issues/29
            \error_log("The session had ended, or at least the encryption key had elapsed.");

            if (strcasecmp("Authentication failed", $re->getMessage()) === 0) {
                return $response->withStatus(302)->withHeader('Location', '/login');
            }
            throw $re;
        }
    }

    protected function renew()
    {
        $settings = $this->settings;
        $name = 'KEY_'.$settings['name'];

        if (empty($_COOKIE[$name])) {
            return;
        }

        setcookie(
            $name,
            $_COOKIE[$name],
            time() + $settings['lifetime'],
            $settings['path'],
            $settings['domain'],
            $settings['secure'],
            $settings['httponly']
        );
    }


    /**
     * Start session
     */
    protected function startSession()
    {
        $settings = $this->settings;
        $name = $settings['name'];

        session_set_cookie_params(
            $settings['lifetime'],
            $settings['path'],
            $settings['domain'],
            $settings['secure'],
            $settings['httponly']
        );

        $inactive = session_status() === PHP_SESSION_NONE;

        if ($inactive) {
            // Refresh session cookie when "inactive",
            // else PHP won't know we want this to refresh
            if ($settings['autorefresh'] && isset($_COOKIE[$name])) {
                setcookie(
                    $name,
                    $_COOKIE[$name],
                    time() + $settings['lifetime'],
                    $settings['path'],
                    $settings['domain'],
                    $settings['secure'],
                    $settings['httponly']
                );
                $this->renew();
            }
        }

        session_name($name);
        session_cache_limiter(false);
        if ($inactive) {
            session_start();
        }
    }
}
```

**Comment by bryanjhv** [comment]
Yeah, I saw it gets auto-registered using `bin/register_secure_session.php`.

At this time, the only viable steps I see are:
- If they include that module, they want it (so it keeps optional).
- If the class it exposes exists (Composer will autoload it), do the work.

So, the only thing missing should be integration with behavior of the module and not with that itself.
If not, you'd need to rewrite a lot of code (theirs and mine), which is what we want not to end up doing.

**Comment by bryanjhv** [comment]
UPDATE: I was testing, and without `autorefresh`, nothing bad happened.
So, everything that needs to be done is inside the `if` in the [Session.php](https://github.com/bryanjhv/slim-session/blob/d2bb057/src/Slim/Middleware/Session.php#L96-L106) file.

https://github.com/bryanjhv/slim-session/blob/d2bb057593be8fe015b86f2a4283f9af2231f6b9/src/Slim/Middleware/Session.php#L96-L106

**Comment by bryanjhv** [comment]
@Danack, if you're still interested in this, I found a solution (really you found it).
The other module expects two `setcookie` calls, for `$name` and `'KEY_'.$name`.

The solution would be inside `if` I pointed, but in general would be: add an option for prefixes (and maybe suffixes) to also refresh, so any other module that does thing like this can be integrated easily.

**Comment by Danack** [comment]
Sorry for not responding, been really busy at work.

tl:dr the code works for me and I realised that really what is needed is a bigger clean-up of PHP's session functionality as otherwise it's still going to be quite fiddly to combine storage of sessions with encryption (or other code) on top of it.
