### ISSUE TITLE
is the session expired correctly?

### ISSUE THREAD

**Issue by torian257x** [bryanjhv/slim-session#22]
https://stackoverflow.com/questions/520237/how-do-i-expire-a-php-session-after-30-minutes/1270960#1270960

**Comment by bryanjhv** [comment]
I looked that before making my package, unfortunately it's not right. If `session.gc_probability` is less than 1, then you loose all session data including that `LAST_ACTIVITY` thing.

If some part of the module is not working for you, please:
1. Read old [issues][] and [pull requests][pr] looking for your problem.
2. If it's not there, see if you can implement it and open a [PR][pr].
3. If that's not possible, make an [issue][issues] sharing context where it fails.

For reference, please read #5, #6 and #7 where the same issue raised.

[pr]: https://github.com/bryanjhv/slim-session/pulls
[issues]: https://github.com/bryanjhv/slim-session/issues
