### ISSUE TITLE
Session helper method to renew settings

### ISSUE THREAD

**Issue by faanahmed** [bryanjhv/slim-session#29]
Hi @bryanjhv , 

Once you have started session with some preset settings, is there any way to update the settings via your helper method, can you please add such method?

For example, updating session lifetime on the fly?

**Comment by bryanjhv** [comment]
That would be problematic, neither professional.
Closest thing is per-route or per-group middleware: https://github.com/bryanjhv/slim-session/pull/26#discussion_r151949781
