### ISSUE TITLE
Cannot remove session key

### ISSUE THREAD

**Issue by NordlingDev** [bryanjhv/slim-session#3]
I can create a session key using this line: `$session->user = 'Test'`
I cannot remove the key using this line: `$session->remove('user')`

The error message I get is: `Call to undefined method SlimSession\Helper::remove()`

EDIT: Documentation seems outdated. `$session->delete()` is now the method to remove a key.

**Comment by bryanjhv** [comment]
Didn't noticed it. Does `SlimSession\Helper::delete()` work fine (I mean, as expected)?

**Comment by bryanjhv** [comment]
It was, as you said, just a problem with the `README`. Solved with df4282d511e953ae9a3ed526e125db27c0ac5af6.

**Comment by NordlingDev** [comment]
@bryanjhv - It does work as expected. Thanks!

**Comment by bryanjhv** [comment]
Thank you for reporting it, any failures you find please keep reporting them. :smile:
