### ISSUE TITLE
Session wiped by gc for not regularly writing to session

### ISSUE THREAD

**Issue by tealborder** [bryanjhv/slim-session#34]
My users log into the site, I write their id to the session and then just read from the session as needed. I never write more to the session other than while signing in. But the garbage collector wipes it clean.

Any suggestions? Here's what someone says on php.net

>There is a nuance we found with session timing out although the user is still active in the session.  The problem has to do with never modifying the session variable. 
>
>The GC will clear the session data files based on their last modification time.  Thus if you never modify the session, you simply read from it, then the GC will eventually clean up. 
>
>To prevent this you need to ensure that your session is modified within the GC delete time.  You can accomplish this like below. 
>
```
<?php 
if( !isset($_SESSION['last_access']) || (time() - $_SESSION['last_access']) > 60 ) 
  $_SESSION['last_access'] = time(); 
?>
```
>
>This will update the session every 60s to ensure that the modification date is altered.

**Comment by bryanjhv** [comment]
Use `ini_settings` option, see [README][].

[README]: https://github.com/bryanjhv/slim-session#supported-options

**Comment by tealborder** [comment]
Turns out debian runs a cron to wipe the session every 30min

**Comment by bryanjhv** [comment]
Locking because it has nothing to do with this package.
Edit `php.ini` with `session.gc_maxlifetime = 31536000`.
Otherwise change `session.save_path` to another location.
