### ISSUE TITLE
doesn't set session when 'secure' => true 

### ISSUE THREAD

**Issue by sieu** [bryanjhv/slim-session#39]
Doesn't seem to set the cookie when secure is set to true.

**Comment by snake14** [comment]
Why was this issue closed?  I'm having the same issue.  When `'secure' => true`, the session cookie doesn't get created, but when I don't include secure, the cookie is created.

Edit:
I think that I figure it out.  In my testing, I'm using http and not https, so the cookie isn't getting created.  I found the following on php.net:
secure
Indicates that the cookie should only be transmitted over a secure HTTPS connection from the client. When set to TRUE, the cookie will only be set if a secure connection exists. On the server-side, it's on the programmer to send this kind of cookie only on secure connection (e.g. with respect to $_SERVER["HTTPS"]).

**Comment by sieu** [comment]
Hey, this is most likely because you’re on localhost, when I uploaded it to
a live site with ssl, it creates the cookie. Hope that helps. It won’t
create a secure cookie if your connection isn’t secure, at least for me.

**Comment by bryanjhv** [comment]
Exactly. Anything related to session cookies is just passed to PHP, so you should read the docs.

https://www.php.net/manual/en/function.session-set-cookie-params.php#97072
