### ISSUE TITLE
Confusion about framework Version 

### ISSUE THREAD

**Issue by DiligentMe** [bryanjhv/slim-session#4]
The description states, "Simple middleware for Slim Framework 3" and sort description says,"A very simple session middleware for Slim Framework 2". Please make it clear

**Comment by bryanjhv** [comment]
Yup, actually it works for both, Slim 2 via `2.x` releases, and Slim 3 via `3.x` releases.
But anyway, you're right, the actual version works for Slim 3. Thanks!
