### ISSUE TITLE
TypeError Session.php

### ISSUE THREAD

**Issue by ghost** [bryanjhv/slim-session#46]
Hi, implementing the last modification: Update to work with Slim Framework 4 I find the problem in the attached photo and with this text: 

Type: TypeError
Message: Argument 2 passed to Slim\Middleware\Session::__invoke() must be an instance of Psr\Http\Server\RequestHandlerInterface, instance of Slim\Http\Response given
File: /vendor/bryanjhv/slim-session/src/Slim/Middleware/Session.php
Line: 74

How can I solve it?

![IMG_20200212_031401](https://user-images.githubusercontent.com/26438200/74296988-c3b93b00-4d45-11ea-8263-718e92ecefca.jpg)

**Comment by bryanjhv** [comment]
Please add complete information.

- PHP version
- Used library version
- Code used to create Slim app
- Code used to register middleware
- Etc

**Comment by ghost** [comment]
@bryanjhv 

PHP version 7.3

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/26438200/74337795-491e0900-4da1-11ea-9c5a-d2066dc4ff83.png)

![image](https://user-images.githubusercontent.com/26438200/74337858-681c9b00-4da1-11ea-938c-16674e818404.png)

**Comment by bryanjhv** [comment]
Here's some help for you:

- Learn how to write on GitHub:
  https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax
  https://help.github.com/en/github/writing-on-github/working-with-advanced-formatting
- Git branching on GitHub:
  https://help.github.com/en/github/administering-a-repository/viewing-branches-in-your-repository
- slim-3 branch on this repository:
  https://github.com/bryanjhv/slim-session/tree/slim-3

Kindly read it all before posting again.
Also, please make sure you know what you're doing.
For reference: you're using Slim 3 Framework this time.
Also add requested information so I don't waste my time reading.
