### ISSUE TITLE
Does not save changes to arrays in session

### ISSUE THREAD

**Issue by stevecoug** [bryanjhv/slim-session#55]
I have an array in my session named "attend". If I am using the session helper, it does not save changes made to that array. For example, the following code does not result in the change being saved in the session:

`$session = new SessionHelper();`
`$session->attend[1] = 2;`

The following does work:

`$attend = $session->attend;`
`$attend[1] = 2;`
`$session->attend = $attend;`

I'm using version 4.0.1 of slim-session.

**Comment by bryanjhv** [comment]
https://github.com/bryanjhv/slim-session/tree/4.0.1#session-helper

```php
// this is just an alternative
// yours might be faster this time
$session->merge('attend', [1 => 2]);
```

AFAIK, there's no way to implement `ArrayAccess` for nested arrays.
And if there is, it's not worth the work. `Helper#merge` already makes it.

**Comment by stevecoug** [comment]
As I understand it, from reading some comments about it elsewhere, you would just need to make the get() functions return a reference. I understand that might have some side effects, though.

**Comment by bryanjhv** [comment]
Please link to these "comments" and its side effects.
If possible you could also submit a PR and i'll take a look.

**Comment by stevecoug** [comment]
It was on this page:
https://stackoverflow.com/questions/2881431/arrayaccess-multidimensional-unset

I'll see if I can make it work and submit a PR. My initial attempts failed, and I ended up just referencing $_SESSION in my class.
