### ISSUE TITLE
Why is the Session class not based MiddlewareInterface?

### ISSUE THREAD

**Issue by Alpine418** [bryanjhv/slim-session#57]

**Comment by bryanjhv** [comment]
The question is not clear.

In case you're asking why doesn't `Session` implement `MiddlewareInterface`:
(AFAIK) Slim Framework doesn't force you to do that, and also I don't mind at all.
At least for me there's no real advantage (apart from adding another method).
If you think there's a clear benefit, please explain and I might change my mind.
