### ISSUE TITLE
slim-session always returns two cookies, one is to delete the cookie

### ISSUE THREAD

**Issue by servicespringcorp** [bryanjhv/slim-session#59]
When using slim-session the response header looks something like this (this is a snippet).

```
Connection: Keep-Alive
Content-Type: application/json
Date: Wed, 24 Feb 2021 17:52:29 GMT
Keep-Alive: timeout=5, max=100
Last-Modified: Wed, 24 Feb 2021 17:38:17 GMT
Set-Cookie: session=t71cabv10mokan4p3mq3hu8s37; expires=Wed, 24-Feb-2021 18:52:29 GMT; Max-Age=3600
Set-Cookie: session=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
```

Note how there's a `Set-Cookie` twice, and one is a delete.  This actually still works just fine if the output is buffered and a `Content-Length:` header value is set.  However, on another server, `Transfer-Encoding: chunked` is set and then it randomly either runs the first or second header `Set-Cookie` so about half the time the session cookie is deleted.

These two sites are running the same cloned repo, so the slim/slim-session settings are identical.  The only difference is that the production server is setup to send chunked data instead of buffering and sending a specific `Content-Length:`.

I looked at the traditional PHP session cookie response header and it just sets the cookie, it doesn't also delete it.  I'm wondering why slim-session is sending this second cookie, as it seems to make things not work in certain cases.

**Comment by servicespringcorp** [comment]
On the server which this isn't working I setup buffering so the `Content_length:` would be set and not `chunked`.  It still doesn't work so buffering isn't the issue.  Not sure why it works on one server and not the other, but it does seem that it shouldn't be telling the browser to delete the cookie in any case.

**Comment by servicespringcorp** [comment]
I believe I know what's up now.  It's strange that it's working on one server and not the other.  I'll close this for now.

**Comment by bryanjhv** [comment]
It'd be useful if you could share more context regarding your setup so I can reproduce it, maybe it's a bug from this library, another one, a conflict from your webserver, and so on.

Specifically:
- PHP (version, session configuration)
- Webserver (name, version, configuration)
- Settings for the `SlimSession` constructor.
- Sample code for your Slim application (and version).
- Anything that would help me reproduce your problem.

Even if you manage to solve it on your own, would appreciate if you share your solution too, so everybody can learn about that.

**Comment by servicespringcorp** [comment]
@bryanjhv Come to find out, I was sending the delete cookie.  What was strange that it worked differently on a development server instead of a production server.  This lead me to believe there was something else going on.  In any case, the issue is resolved, slim-session was not at fault.

**Comment by bryanjhv** [comment]
Thank you for the update!

I haven't experienced that issue locally but understand that development environments tend to make life easier by using some shortcuts/settings which break on production.
