### ISSUE TITLE
Check if a session is started

### ISSUE THREAD

**Issue by svanlaere** [bryanjhv/slim-session#8]
To prevent "A session had already been started - ignoring session_start()" notice
its better to check first if its needed to start one yourself:
`if ( session_status() == PHP_SESSION_NONE ) {
    session_start();
}`

**Comment by bryanjhv** [comment]
Well, now that the package also depends on PHP 5.5 it can be done. ~~But, just a question: why not to use `session_id` instead of `session_status`?~~

~~More info: http://php.net/manual/en/function.session-status.php#111945~~

**Comment by bryanjhv** [comment]
Thanks for the issue. Let's follow it via #9 :smile:

**Comment by svanlaere** [comment]
Does it not resolve the issue?

**Comment by bryanjhv** [comment]
First at all, it's just a notice. I left a review on #9 so please read that first.
